INSERT INTO ROLE_INFO (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Developer', 'Beginner level programmar');
INSERT INTO ROLE_INFO (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('Tester', 'Tester Joiner Level');
INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, GENDER, ROLE_NAME) VALUES ('rajesh', 'kumar', 'male', 'Developer');
