CREATE TABLE EMPLOYEE(
  EMP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRSTNAME VARCHAR(16) NOT NULL,
  LASTNAME VARCHAR(16) NOT NULL,
  GENDER VARCHAR(10) NOT NULL,
  ROLE_NAME VARCHAR(16) NOT NULL
);

CREATE TABLE ROLE_INFO(
  ROLE_NAME VARCHAR(16) NOT NULL PRIMARY KEY,
  ROLE_DESCRIPTION VARCHAR(256) NOT NULL
);

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (ROLE_NAME) REFERENCES ROLE_INFO(ROLE_NAME);